variables:
  SERVICE_FRONTEND_PATH: "./React-Project/FrontEnd"

stages:
  - deploy
  - clean
  
# 프론트엔드 서버 배포 작업 정의
deploy_frontend:
  stage: deploy
  script:
    - echo "프론트엔드 관련 설정 도커 컨테이너 배포 중..."
    - cd $SERVICE_FRONTEND_PATH
    - docker-compose -f docker-compose-frontend.yml down --volumes react_service nginx_service
    - docker-compose -f docker-compose-frontend.yml up --build -d react_service nginx_service

clean_frontend:
  stage: clean
  script:
    - docker stop react || true
    - docker rm react || true