services:
  react_service:
    container_name: react  # 컨테이너의 이름을 설정합니다.
    build:  # 도커 이미지 빌드 관련 설정입니다.
      context: .  # Dockerfile이 위치한 디렉토리 경로입니다.
      dockerfile: React.Dockerfile  # 사용할 Dockerfile의 이름입니다.
    image: todolist_frontend_img  # 빌드된 이미지의 이름을 설정합니다.
    volumes:
      - react_build:/usr/src/app/dist  # 빌드 결과물을 볼륨에 저장
    entrypoint: ["true"]  # Docker 이미지가 빌드되고 볼륨이 준비된 후에 컨테이너 실행을 즉시 종료

  nginx_service:
    container_name: nginx
    build:
      context: ../CICD/Nginx
      dockerfile: Nginx.Dockerfile
    volumes:
      - react_build:/usr/share/nginx/html  # Nginx가 빌드된 정적 파일을 서빙
    ports:
      - "80:80"
    networks:
      - todo-net
    depends_on:
      - react_service # 의존성을 리액트 서비스명으로 설정

volumes:
  react_build:  # 공유 볼륨 선언

networks:
  todo-net:  # 사용할 네트워크를 정의합니다. 
    name: todo-net
    driver: bridge