variables:
  SERVICE_INFRA_PATH: "./React-Project/CICD"

stages:
  - deploy

# 인프라 관련 배포 작업
deploy_infra:
  stage: deploy
  script:
    - echo "인프라 관련 설정 도커 컨테이너 배포 중..."
    - cd $SERVICE_INFRA_PATH

    # PostgreSQL 컨테이너 실행 상태 확인
    - echo "PostgreSQL 컨테이너 실행 상태 확인 중..."
    - isPostgresRunning=$(docker ps --filter name=postgresql --filter status=running --format '{{.Names}}') || true
    - echo "PostgreSQL 실행 상태 = '${isPostgresRunning}'"

    # PostgreSQL이 실행 중이지 않을 때만 Docker Compose로 실행
    - |
      if [ -z "${isPostgresRunning}" ]; then
        echo "PostgreSQL 컨테이너가 실행 중이 아닙니다. Docker Compose로 PostgreSQL 실행하겠습니다.";
        docker-compose -f docker-compose.yml --env-file .env-postgresql up --build -d postgresql_service;
      else
        echo "PostgreSQL 컨테이너가 이미 실행 중입니다.";
      fi